### ISSUE TITLE
Bảng chú giải dịch thuật

### ISSUE THREAD

**Issue by ImVietnam** [javascript-tutorial/vi.javascript.info#218]
Tôi thấy chúng ta cần một bảng chú giải dịch thuật giống như https://github.com/reactjs/vi.react.dev/issues/2 để thống nhất những từ cần dịch và từ nào không

**Comment by tunggnu** [comment]
Hợp lý. Bạn hãy tạo bảng đó ở trong khu vực thảo luận: https://github.com/javascript-tutorial/vi.javascript.info/discussions
