### ISSUE TITLE
Duplicate slug

### ISSUE THREAD

**Issue by tttam0113** [javascript-tutorial/vi.javascript.info#85]
There are 2 pairs with same slug:
- 1-js/02-first-steps/06-alert-prompt-confirm **vs** 1-js/02-first-steps/09-alert-prompt-confirm
- 1-js/06-advanced-functions/11-currying-partials **vs** 1-js/99-js-misc/03-currying-partials

These causes an error when i try to run the tutorial locally at <https://github.com/javascript-tutorial/server>

There are some articles which have wrong the number in 1-js/02-first-steps.

**Comment by tunggnu** [comment]
This issue will be resolved by the pull request #113.
